### ISSUE TITLE
CLI flags for specific categories of deletion

### ISSUE THREAD

**Issue by riotrah** [seachicken/gh-poi#127]
**Description**
Hi!

Great extension.

I was thinking about my own usage of this tool, plus #119, and thought about the following more general proposal to choice in deletion:

- `poi` offers a couple new flags:
	- `--closed`/`--no-closed`
	- `--merged`/`--no-merged`
	- `--draft`/`--no-draft`
- these can be combined per user's wishes: `gh poi --closed --merged`
- where, if unspecified, `--merged` is defaulted

Or, slight alternative: `--merged` is always true, thus no need for `--merged` flag, so if the user runs `gh poi --closed`, it will delete both merged and closed PRs. However, if they only want to delete closed PRs, they can still do `gh poi --closed --no-merged`.

**Additional context**

When would you use `poi` to delete other than merged branches? Isn't that the whole point? I think `poi` has nice output, branch protection, `--dry-run` feature and convenient access with `gh`, so it has value even if only deleting closed/draft, as the alternative of manual deletion is worse and lacks the above features/protections, and I don't think it would be too hard to add such flags (as far as I can tell, correct me if I'm wrong!)

**Comment by seachicken** [comment]
Thank you for the good suggestion 😄 I sometimes want to delete "closed," too and I think it would be better to have the option to delete it since we can check it with a dry run.

The main thing to consider is what to do with the interface of the options.
Since this tool is a command that starts with "gh," we place importance on affinity with the gh interface so that users can operate it intuitively. Since exclusion with `--no-xxx` probably falls outside this policy, how about adding targets like [gh pr list](https://cli.github.com/manual/gh_pr_list)?

- `gh poi --state closed` (currently gh seems to include closed and merged https://github.com/cli/cli/issues/8102)
- `gh poi --draft`

>However, if they only want to delete closed PRs, they can still do gh poi --closed --no-merged.

There are very few cases where you would want to delete only closed PRs, so it is better to start by only allowing the deletion of merged and closed PRs.

**Comment by seachicken** [comment]
There are very few cases where we want to delete a draft PR, so I will close it without implementing it.
